server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.31
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.32:${server.port}/eureka/,http://192.168.1.33:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true